version: '3.8'

services:
    web:
        build: .
        image: rails-docker
        restart: "no"
        environment:
            - DBHOST=postgresql
            - DBUSER=ymow
            - DBPASS=1111
        ports:
            - 3000:3000
        depends_on:
            - postgresql

    postgresql:
        image: postgres
        restart: "no"
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: docker_rails_development
            POSTGRES_USER: ymow
            POSTGRES_PASSWORD: 1111
        volumes:
            - postgresdb:/var/lib/postgresql/data/

volumes:
    postgresdb:
